services:
  discord-bot:
    build: 
      context: .
      args:
        BUILD_DATE: ${BUILD_DATE:-$(date +%s)}
    restart: unless-stopped
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - DISCORD_OWNER_ID=${DISCORD_OWNER_ID}
      - DISCORD_GUILD_ID=${DISCORD_GUILD_ID}
      - ROLE_CHANGES_ID=${ROLE_CHANGES_ID}
      - ROLE_STATUS_ID=${ROLE_STATUS_ID}
      - ROLE_PICK_CHANNEL_ID=${ROLE_PICK_CHANNEL_ID}
      - PIPED_API_BASE=${PIPED_API_BASE}
      - PIPED_FRONTEND_BASE=${PIPED_FRONTEND_BASE}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - TZ=America/Chicago

  frontend:
    build: ./frontend
    ports:
      - "3501:3501"
    restart: unless-stopped
