services:
  discord-bot:
    image: python:3.12-slim
    working_dir: /app
    # pull your code into the container at runtime
    volumes:
      - ./:/app:ro
      - pip-cache:/root/.cache/pip
    command: sh -c "pip install --no-cache-dir -r requirements.txt && python main.py"
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - TZ=America/Chicago
    restart: unless-stopped
    # no ports (Discord bot connects out)

volumes:
  pip-cache:
